Dockerfile, spackbot/__main__.py, spackbot/pr_add_labels.py, spackbot/pr_add_reviewers.py
This PR does a number of things:
=> Rework spackbot: security fixes and use a team for maintainers

spackbot/pr_add_labels.py
The 'update-package' label was being added to PRs that don't update any packages: https://github.com/spack/spack/pull/24590
=> Only add 'update-package' label for packages

.env-dummy, .gitignore, README.md, docker-compose.yml, smee/Dockerfile, smee/entrypoint.sh
This is the start of work to add more details in the README for setting up a development server, and adding docker-compose containers that provide both spackbot and smee (so the user doesn't have to install on their host).
I've tested this up through running the containers and seeing the services start, and I wanted to ask folks here about the best way to develop with the app? I was thinking of making a clone of spack or other dummy repo on my user account, installing the app there, and then developing that way. Is that a reasonable approach?
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Start of work to provide complete instructions for development

.env-dummy, README.md, requirements.txt, spackbot/__main__.py, spackbot/helpers.py, spackbot/pr_add_labels.py, spackbot/pr_run_pipeline.py
This PR will add support for asking spackbot to re-run a pipeline! I tested this with cancelled pipelines and the triggers worked. It works by way of checking if the person has write, and if so, allowing them to trigger the endpoint to run the GitLab branch.
I duplicated helpers.py since I needed the found function, which is in the other PR.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Adding ability for spackbot to re-run a GitLab CI pipeline

spackbot/comments.py
Instead of running spack blame and spamming people, we can add a note to the PR opener to use it to find people that have worked on the package. This will close #4.
=> Adding note about spack blame

spackbot/comments.py, spackbot/handlers/reviewers.py
Instead of always using zlib as a blame example, use the actual list of unmaintained packages so contributors can simply copy and paste.
=> Show blame commands for unmaintained packages

spackbot/handlers/labels.py
I recently changed the 'smoke-tests' label to 'stand-alone-tests' but did not realize spack-bot knew to label PRs until someone pointed one out to me.
This PR replaces the old label with the new one.
=> Change smoke-tests to new stand-alone-tests label

requirements.txt, spackbot/comments.py, spackbot/handlers/pipelines.py, spackbot/handlers/reviewers.py, spackbot/handlers/style.py, spackbot/helpers.py, spackbot/routes.py
This will close #33 I could easily test the style and joke requests. I don't like needing to provide the gh client to the helper functions, but I guess it's not that important.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Removing requests library as dependency

spackbot/handlers/labels.py
Closes #38 
The `commands` label was only being added if a command file was modified.  This PR will add it for any status (so we add two labels for a new command).  It also adds the label for command test files.
=> commands: add label for new/renamed commands *and* command tests

.github/workflows/build-deploy.yaml
This will deploy to GitHub packages on PR (just build) and merge to main (build and deploy) and always deploy a latest along with a tag "versioned" by the git sha, just in case we need to easily go back to an old one
We will need to add someone's username with access to packages to GHCR_USERNAME in the repository secrets.
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Adding workflow to build and deploy the spack bot container

README.md
Fix the GH pages documentation link.
Note: do not forget to update the repo URL as well.
=> README: Fix Doc Link

spackbot/handlers/pipelines.py
This change intends to shed some light on situations when spackbot has a problem triggering pipelines by logging gitlab's response to the pipeline api request.
=> Print debug information on pipeline trigger errors

spackbot/handlers/pipelines.py
Based on some local testing, making gitlab api requests using urls with reserved characters like `+` results in failure, while using urllib to encode the branch names first results in success.  Hopefully this change will fix issues reported with spackbot responding "I had a problem triggering the pipeline", as seen on this spack [PR](https://github.com/spack/spack/pull/25821).
=> URL encode branch names in case of reserved chars

.env-dummy, .github/workflows/build-deploy.yaml, Dockerfile, docker-compose.yml, entrypoint.sh, requirements.txt, spackbot/__main__.py, spackbot/auth.py, spackbot/comments.py, spackbot/handlers/labels.py, spackbot/handlers/pipelines.py, spackbot/handlers/reviewers.py, spackbot/handlers/style.py, spackbot/helpers.py, spackbot/routes.py, spackbot/workers.py, workers/Dockerfile, workers/entrypoint.sh, workers/requirements.txt
To get spackbot main deployable again, try to fix the current bug by performing the long-running style fix in another process using the `rq` (Redis Queue) module.  This brings some of the functionality from #45, so we'll need to revisit that if this gets merged first.
This will need to be coupled with a change to `spack-infrastructure` as well, in order to provision a deployment for the worker and a connection to redis.
Arguments sent to worker functions have to be stored in redis, and as such, I think it's best to avoiding sending complex objects (pickling is the default argument serializer I believe).  I could be wrong, so some testing is in order to be sure.  ~For this reason, I'm currently not sending the `gh` object to the worker, so once we ship the task, we can no longer post …
=> Add support for fixing style as a task in another process

spackbot/__main__.py, spackbot/handlers/style.py, spackbot/workers.py
According to the ghapi docs, the token should be good for one hour
from the time you request.  So instead of having the worker attempt
to re-authenticate the installation as soon as it starts (which so
far has been pretty much immediately), let's just use the token we
already put in the job metadata to communicate with the api.
If we ever see that the worker is taking more than an hour to get
kicked off or do it'w work, we can revisit this.
=> workers: Do not attempt to re-auth installation

spackbot/handlers/labels.py
Noticed in logs that we sometimes fail to apply labels due to a bug where we post a lot of duplicates.  Here's an example from a recent log file:
```
INFO:spackbot.handlers.labels:Adding the following labels: ['update-package', 'update-package', 'maintainers', 'new-version', 'patch', 'update-package', 'maintainers', 'new-version', ..., 'new-version']
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/app/spackbot/__main__.py", line 54, in main
await router.dispatch(event, gh, session=session, …
```
=> labels: dedup labels before posting

.env-dummy, spackbot/routes.py, spackbot/workers.py, workers/entrypoint.sh
Without this, and considering we had only a single redis instance backing both the production and development deployments, it was arbitrary which deployment would pick up enqueued tasks (dev vs production).  So a worker from the dev deployment would randomly pick up a task enqueued by the production spackbot webservice, or vice versa, and in this case it would not have any of the correct secrets to successfully complete the job.  This change makes the queue name an environment variable so the two deployment environments can use distinct work queues in the same redis instance.
=> Customizable queue name

spackbot/comments.py
Single quotes will fail Spack's Black checks.
=> comments: Fix quotes

.env-dummy, docker-compose.yml, redeploy-spackbot-dev.sh, requirements.txt, spackbot/handlers/__init__.py, spackbot/handlers/gitlab.py, spackbot/handlers/mirrors.py, spackbot/handlers/pipelines.py, spackbot/handlers/style.py, spackbot/helpers.py, spackbot/routes.py, spackbot/workers.py, workers/Dockerfile, workers/entrypoint.sh, workers/install_aws.sh
=> Pr graduation

workers/requirements.txt
I confirm `spackbot fix style` doesn't work currently. My working hypothesis is that we might be installing some conflicting Python package in this image, since spack now appends to `sys.path`.
I'll check that out, but reading through `requirements.txt` I am pretty sure we were installing black all the time - which now also installs all the other three. Submitting this fix under the assumption that is not an issue to build and deploy this image regularly (or on demand) but let me know if this is not the case and we should seek another fix.
=> Add black and clingo to the list of preinstalled packages

spackbot/handlers/reviewers.py
Fixes a bug I introduced in #73.
Only the old syntax was detected properly:
```pycon
>>> import re
>>> old = 'maintainers = ["a", "bc", "d"]'
>>> new = 'maintainers("a", "bc", "d")'
>>> re.findall(r"maintainers\s*=\s*\[[^\]]*\]", old)
['maintainers = ["a", "bc", "d"]']
>>> re.findall(r"maintainers\s*=\s*\[[^\]]*\]", new)
[]
```
Neither worked 😅 
```pycon
>>> re.findall(r"maintainers(\(|\s*=\s*\[)[^\]\)]*(\)|\])", old)
[(' = [', ']')]
>>> re.findall(r"maintainers(\(|\s*=\s*\[)[^\]\)]*(\)|\])", new)
[('(', ')')]
```
Both work:
```pycon
>>> re.findall(r"maintainers(?:\(|\s*=\s*\[)[^\]\)]*(?:\)|\])", old)
['maintainers = ["a", "bc", "d"]']
>>> re.findall(r"maintainers(?:\(|\s*=\s*\[)[^\]\)]*(?:\)|\])", new)
['maintainers("a", "bc", "d")']
```
The regex below it does not require updating: …
=> Fix regex for detection of reviewers

spackbot/workers.py
Currently we print out:
> But it looks like I'm not able to push to your branch.
> Did you check maintainer can edit when you opened the PR?
When `spackbot` can't write to a PR branch.  We should link to what we're talking about here.
This changes the last part of the text to:
> Did you check [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) when you opened the PR?
Which should hopefully help people understand what we're asking for.
=> Add link to GitHub's instructions for allowing edits from maintainers

README.md, docs/docs/README.md, docs/docs/developer-guide/developer-guide.md, docs/docs/developer-guide/docker-compose.md, docs/docs/index.html, docs/docs/support.md, docs/index.html, pyproject.toml, spackbot/comments.py
The "github-actions" button on https://spack.github.io/spackbot/ is broken. I don't think https://github.com/apps/spack-bot or any permutation of that actually exists. Let's just remove the button.
=> Remove github-actions broken link

spackbot/handlers/labels.py
This PR updates the regular expression for the stand-alone tests label to pick up changes to methods that use the new naming convention (i.e., methods starting`test_`).
=> Update regex for stand-alone-tests label

spackbot/workers.py
I've noticed that pipelines are generated a lot of unnecessary jobs (rebuild jobs that find there's nothing to rebuild).  This led me to notice that none of the stacks within the `shared_pr_mirror` have an index, and from there that the `spack buildcache update-index` command used here is out of date.
I'm not sure why even with the `-d` argument to the command, we don't see any errors in the `lworkers` log, but this PR should fix the issue updating the mirror indices so pipelines can stop generating those unnecessary jobs.
=> Remove unrecognized cli argument from buildcache command

spackbot/helpers.py, spackbot/workers.py
Supports a recent change to spacks gitlab pipelines requiring an additional environemnt variable to be specified when the pipeline should rebuild all packages.
This will be needed for "@spackbot rebuild everything" to work after this spack [PR](https://github.com/spack/spack/pull/39939) is merged.
=> Update how "@spackbot rebuild everything" is done

Dockerfile, spackbot/routes.py, workers/Dockerfile, workers/requirements.txt
Update the image for spack-bot web service and spackbot-workers to match the expected development environment for Spack.
Latest Spack environment is using ubuntu:22 -> python 3.9.
Instead of relying on spackbot encoded requirements for the style check, directly fetch the style check requirements from spack/develop
=> Update the worker image to reference Spack for style requirements

spackbot/handlers/labels.py, spackbot/helpers.py
due to https://github.com/spack/spack/pull/49275, builtin packages are
now located at `var/spack/repos/spack_repo/builtin`
Once the package repo is fully split from core, we'll probably need a
follow-on PR to change the `spack_develop_url`  in `spackbot/helpers.py`
=> fix builtin path
